#pragma once
#include <string>
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <iostream>
#include <sys/time.h>
#include <pthread.h>
#include <sstream>
#include <vector>
#include <unordered_map>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/sendfile.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <pthread.h>
#include <queue>
using std::cout;
using std::endl;
